### ISSUE TITLE
Generalizing from weekly aggregation

### ISSUE THREAD

**Issue by vnminin** [klumbard/covidWeekly#1] opened 2020-04-03 18:42 UTC
Would it be possible to have the time intervals being set by a user, so we can try aggregating by 3 days or 10 days, etc?

I think it could be useful...

**Comment by klumbard** [comment] 2020-04-03 19:01
I agree, I think it would be nice to have that and set the default to be by-week as it is now. I'm working to add options for dealing with absent negatives, but after that I can work on this.

**Comment by klumbard** [comment] 2020-04-06 19:29
Hi guys, I've been working on this and have it pushed to the development branch named "arbitraryAggregation". I think the code for aggregating over arbitrary intervals is working as intended (it passes unit testing), but I want to mess around with it and make sure it's not doing anything weird for another day or two before merging with master.

If you guys would like to start using this either for actual analysis, or just help me test out the new functionality and look for weird results, you can do:

`install_github("klumbard/covidWeekly", ref = "arbitraryAggregation")  
`  
  
Also keep in mind that the new default argument for dealing with missing negatives is to remove those rows (`absent_negs = "remove"`), so if you'd prefer to sum over those like we had been doing before, you need to invoke` absent_negs = "collapse"`.

So an example function call would be:
`dat <- covidWeekly::get_state_dat(absent_negs = "collapse", agg_interval = 7)`

**Comment by klumbard** [comment] 2020-04-22 13:04
This has been merged with master and is now the default functionality.

**Closed as completed** 2020-04-22 13:04 UTC
